apiVersion: v1
kind: Service
metadata:
  name: python-frontend
  labels:
    app: python-frontend
spec:
  type: LoadBalancer
  selector:
    app: python-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
